### ISSUE TITLE
Add support for Mame

### ISSUE THREAD

**Issue by Emulga** [cosmo0/arcade-manager#19]
Support for Mame on computer, installing the overlays in the artwork directory of Mame.

**Comment by cosmo0** [comment]
Hello,

These overlays have the RetroArch format, and only work on RetroArch.

The source of the overlays are MAME overlays/bezels, and can be found here: https://forums.libretro.com/t/my-realistic-arcade-bezels/10604 or here: https://github.com/cosmo0/retropie-overlays-arcade-realistic/tree/master/_sources or here: https://github.com/cosmo0/retropie-overlays-arcade-artwork/tree/master/_sources

You can just download and install them as any regular MAME overlay/bezels.

**Comment by Emulga** [comment]
If anyone comes across this you'll be interested in looking at the Bezel Project for Windows that does exactly this.

https://github.com/thebezelproject/BezelProject-Windows/releases

**Comment by cosmo0** [comment]
Nice! Too bad it's only for Windows, though.

**Comment by Emulga** [comment]
Actually it works for anything since it works for Retroarch.

https://prnt.sc/104a0n1

**Comment by cosmo0** [comment]
Yeah but you have to run it on a Windows computer.

It's interesting, though. Maybe when I have time to finally update/upgrade this project I'll take a few ideas from there.

Thanks for the info :)

**Comment by Emulga** [comment]
What I like about your version is that there's no TV in the overlays. It would be nice to have the option of without or without the TV!
