### ISSUE TITLE
Installation of overlays does not complete

### ISSUE THREAD

**Issue by movisman** [cosmo0/arcade-manager#2]
Hey,

I thought i'd give the arcade-manager a whirl - I installed the overlays I needed manually, but I wanted to check it out as it'd definitely save me a lot of time in the future.

I'm not pointing the tool at my RetroPie share, as i'm sorting the roms and overlays out on my PC, and then i'll SFTP them across via FileZilla when ready. Dunno if this is the cause of any of the issues I encountered, but worth mentioning.

Anyway, I selected my ROMs folder (which have 107 0.203 roms inside), and I selected an empty folder for the configs.

Hit start, and for some reason it gets all the way to S, completes simpsons.zip but doesn't do the rest. It 'completes', I think it managed 87 or something. The bar goes all the way across. It's like when it does it's calculations at the start, it seems to ignore those roms at the end of the alphabet. Kind of odd. So I deleted all the roms all the way up to the failures and started again, and it didn't obtain overlays for any of those remaining roms, even though overlays exist for them. Pop the other files back in and it'll do 87 again. So it had a real problem from part of S through to Z. This is installation of arcade-artwork btw, not the realistic ones. Hard to explain the issue, but if I can export any sort of log I can obviously send it to you.

I was able to replicate this on Linux and Windows every time, it was most strange.

Not sure if you have any ideas, or how often you are working on the tool - but was an odd thing indeed. Especially as I could replicate across two totally different machines on two different OS's.

Anyway thought it was worth mentioning it in case it helps.

Cheers!

**Comment by cosmo0** [comment]
Hi!

Thank you very much for your precious feedback.

I'm using Github API to get the list of available files. Looking at your bug report, and checking the API, I'm finding that they limit the results to 1000, just like in the files browser, and the files stop at swobros. I mostly test with realistic overlays, which don't have this problem (there aren't 1000 of them) and didn't think of that. I'll have to create a list myself, not relying on Github.

Thank you! I'm in the middle of adding new features, and don't spend enough time on this tool anymore. I'll try to at least fix this bug soon.

**Comment by movisman** [comment]
Hey there!

No worries at all!

That makes total sense, thanks for clarifying that. I was wondering what was happening as it was a bit strange! No probs, I wasn't sure how much time you would be spending on this tool, if you fix the bug great, if not - no worries!

On a side note, thanks for supplying the overlays for both console /  arcade in your repositories and making a great collection for people to use. It has saved me a lot of time scouring the net and I really appreciate it.

Cheers

**Comment by cosmo0** [comment]
Thanks! I'm always glad when someone tells me they use my repository :)

Next version will be able to switch overlays resolution on the fly, as well as some minor issues fixed or improved: https://github.com/cosmo0/arcade-manager/projects/1

I'm trying to detect clones to install parents, but it's proving a bit harder than expected, especially since I don't know javascript enough (I'm not such a fan of those "promises").

**Comment by cosmo0** [comment]
I have fixed the issue and published a new release (clone detection will be done later). Let me know if you find any issue! Thanks :)

**Comment by movisman** [comment]
Awesome! Thanks so much. I'll give v5.0 a try and let you know if there are any issues with it.

Regarding clones, yes that would be useful, I probably have 6-7 clones (mostly 2 player variants) and when I used your overlays I just made manual copies and renamed some files so the overlay would appear for both parent and clone. If the app was able to detect the clone but install the overlay from the parent that would be really neat.

Cheers!

**Comment by protoman** [comment]
I have the same issue. Picked just a few (6) roms, put on a folder, and get stuck into the "Processing files list" dialog.

**Comment by cosmo0** [comment]
@protoman after more than a year I won't ask for a log (sorry) but were you too installing using Linux by any chance?

**Comment by protoman** [comment]
Yes, it was on linux mint.
--
Iuri Fiedoruk, Software Developer

**Comment by cosmo0** [comment]
@protoman thanks for the answer!

There's a weird bug where on Linux (and only Linux) it stops at the start of the download, and doesn't tell me why, debugging says nothing. It just stops.

Maybe upgrading to the latest Electron version would fix the problem (it uses Electron 4 but the latest is 12), but I would have to basically rewrite the whole project since they blocked a few things I do in v5 :(

I'll try to fix it later, for now I'll focus on checking/fixing Recalbox integration.

**Comment by cosmo0** [comment]
@movisman @protoman I've changed the app language (converted it from NodeJS to .Net), would you be interested in trying it, see if it fixes the issue?

**Comment by protoman** [comment]
Sure, I will do that. I need to backup my retropie on my pc anyway :)
Will let you know of the results.
--
Iuri Fiedoruk, Software Developer

**Comment by cosmo0** [comment]
@protoman  Sorry there was a huge bug in the previous version (I didn't test with Retropie and it just didn't work)

Here's the new link: https://we.tl/t-JNLjKXTR99

**Comment by protoman** [comment]
Yes, no problem being 16:9, I just need to do an approximation, as 768p
ends up with a non-integer value when calculating 16:9 ratio :)
Let me see if I can get something near and I will let you know of the
results.
--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
OK, I found a resolution that is very near. I will upload it to retropie
and check how it is.
BTW, after the overlays installation is complete, it just shows "0
installed" instead of the real number it did download and install.
--
Iuri Fiedoruk, Software Developer

**Comment by cosmo0** [comment]
> BTW, after the overlays installation is complete, it just shows "0 installed" instead of the real number it did download and install.

Are you sure it has downloaded and installed the overlays?

So it means it works now? :)

> Also, while I did run with 1360x765 resolution, the downloaded image is 1080p

Yeah the image is not resized, only the output resolution ; it's enough to improve performances on a Raspberry Pi. I'll resize the images if I allow resolutions other than 16:9.

> and the config file does not have any adjustments for resolution:

The resolution is in the rom config ; check the "xxxx.zip.cfg" that's been copied alongside your roms (if you're using Retropie).

**Comment by protoman** [comment]
Oh, I see, I tough the configs were placed in the configs folder, not also
in the roms folder, forgot how it worked, it's been a while since I changed
things there.
Yes, the app created the .zip.cfg in the roms folder, a .png and .cfg in
the configs folder, so I would say it did install :)
And yes, I am using a retropie, I'm just running over a directory copy on
my Linux PC, so I don't overwrite the configs I already have there.
--
Iuri Fiedoruk, Software Developer

**Comment by cosmo0** [comment]
Cool! Please let me know if everything works when you run a game :)

**Comment by cosmo0** [comment]
@protoman have you been able to test the new version? :)

**Comment by protoman** [comment]
Hey, sorry. Looks like my reply from march 31 was rejected but I did not receive any feedback from my email, so let me try to post by the web-version of github:

Perfect, just perfect!
It did adjust the sizes for my screen resolution (a similar one, but the few pixels difference don't matter) both vertical and horizontal.
Now I just have to organize and run over other arcade games.

This is my machine: https://photos.app.goo.gl/bM5FGTUBtoQmJXjo9
Vertical game: https://photos.app.goo.gl/ydA96WLCZSGCLiKw6
Horizontal game: https://photos.app.goo.gl/cSrXGSNn1LyopYe28

Thank you very much, this new version ROCKS big time \o/

**Comment by cosmo0** [comment]
Thank you for your feedback! I'm glad that it works 😄 

I'll make a new version using .Net after I add a few features. Thanks again!
