### ISSUE TITLE
Unusable converted *.dat file

### ISSUE THREAD

**Issue by Oxyur** [cosmo0/arcade-manager#22]
Hello,

First, thank you very much for arcade manager, I've gained so much time with it.

I used the "convert to *.csv" function on a dat file coming from there : https://github.com/libretro/FBNeo/tree/master/dats 

It was ok creating it.

I splitted it in both parts with reCsvEditor, one for parents, other one for clones

When I try to use it with arcade manager, for example for copying roms, the parents list functions. But with the clone one I have this error : 
"Error: Uncaught Error: Invalid Closing Quote: got "]" at line 688 instead of delimiter, record delimiter, trimable character (if activated) or comment"

So, I tried to figure why this *.csv list doesn't function, and compared it with the ones downloadable from arcade manager. I give you 1st the line 688 given in the error, and a random game for example.

My csv converted dat file 
==> cthd2k3a;"Crouching Tiger Hidden Dragon 2003 (set 2)  [Bootleg]";2003;"bootleg";NO;kof2001;YES;kof2001;-
==> 1945kiii;"1945k III (newer, OPCX2 PCB)";2000;"Oriental Soft";YES;-;NO;-;-

Arcade manager list (fb neo): 
==> (there is no official clone list in arcade manager so I can't compare cthd2k3a)
==> 1945kiii;1945k III (newer, OPCX2 PCB);2000;Oriental Soft;YES;-;NO;-;-

Here, the " are the only difference.

Some programs (including arcade manager) tell me that there is a difference in closing quotes between the 2 lists. But I don't see any.
The "]" appears all over the lists, I don't see why it could make a problem with one and not the other one.

Then, is there some thing to do on arcade manager to make my new csv to function ?
Or do I have to convert in some other csv format ?
Is there a simple fix to apply on the list ?
Or the problem is something different I haven't understood or noticed ?

Thank you for helping me when you'll have some time.

Have a good day,

Regards,

Oxyur

**Comment by cosmo0** [comment]
@Oxyur 
Hello and thank you for your bug report.

I'm glad you find it useful :)

I can't make ReCsvEditor work. Could you provide me with the files you're trying to use? You can upload them in this issue (just drag & drop the file on the textbox).

**Comment by TVsIan** [comment]
The quotes seem to be the issue here. I used the MAME .228 Datfile from progetto-snaps (https://www.progettosnaps.net/dats/MAME/), and it converted Ok but failed when trying to work with the csv. I loaded it up in Notepad++ and deleted all the quotes, and it worked afterwards.

It looks like the conversion function needs to not output quotes to work.

**Comment by cosmo0** [comment]
![image](https://user-images.githubusercontent.com/3973850/198853202-a5f607e0-39c4-46b8-a346-bfee5dad445b.png)

@Oxyur  sorry it took me so long to check a CSV file, I think I fell into a wormhole or something.

In the "Clones - 4318.csv" file, line 688, you can see that `Hack of The King of Fighters 2001"]"` a quote before the caret. That's the source of the error: removing it works fine.

I'm not sure I can build better error messages, they come from the CSV parsing library I use.

I'm closing this bug, assuming you'll never look at it, but feel free to reopen it.

**Comment by Oxyur** [comment]
Hey !

I was also in a cryogenic tube waiting for a new world to come, then your
mail awakened me. Future doesn't seem better, BUT I have an answer...

[image: proxy-image.jpg]

Trying to find the solution was on my to-do list for a long time.

So the error message was relevant, but the line where I was searching was
not the good one, for some reason I don't understand, maybe I don't use
good tools to edit them.

A lot of trouble for a little quote.

Thank you very much, now I can finish this.

Have a good one ;-)

**Comment by cosmo0** [comment]
Merci :)
