### ISSUE TITLE
Appveyor Links Broken

### ISSUE THREAD

**Issue by Crono141** [cosmo0/arcade-manager#23]
When trying to download binaries from any of the links to appveyor, I get a "project not found or access denied" error.

**Comment by cosmo0** [comment]
@Crono141 sorry it took me so long to get back to you.

Appveyor has a policy of keeping artifacts for one month.

You can download the latest release using the "releases" page: https://github.com/cosmo0/arcade-manager/releases

Or you can build the app yourself using the instructions at the end of the readme.
