### ISSUE TITLE
Tool does not support/recognize 7zip files.

### ISSUE THREAD

**Issue by dahui** [cosmo0/arcade-manager#24]
Many modern MAME sets found on the internet come as 7zip files rather than zip files in order to save space. At the moment, the tool does not recognize these files as valid as it only supports Zip. 

Looking at the code, it appears the fix could be as simple as having it check for a zip or 7z file instead of only zip. I am not a C# developer though so I may be oversimplifying things here.

It may be beneficial to add an option to specify the extension the files are saved as in order to future proof the copying behavior.

**Comment by cosmo0** [comment]
Hey! Sorry to have kept you waiting for so long.

I'm adding support for `.7z` in the next release. I'll close this issue, feel free to reopen it if you want/need. And if you're still around and interested in the feature, obviously.
