### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hregis** [cosmo0/arcade-manager#25]
Hello,
How to install Arcade Manager with Batocera PC ?
sorry i'm a newbee ! ;-)
Thank you for your work

**Comment by cosmo0** [comment]
@hregis Hey! Sorry I kept you waiting so long.

The tool is supposed to be used on a different PC, running Windows, Linux or MacOS. It then connects to your Batocera PC to manage its files, using a network share, for instance.

Please note that the tool doesn't support Batocera at the moment.
