### ISSUE TITLE
[Question] Can I use arcade manager for this purpose?

### ISSUE THREAD

**Issue by d-apps** [cosmo0/arcade-manager#26]
Hi,

I have a folder with 15 GB of roms ( FBN collection), I wanted fighting games mostly and some others few games with different genres, I'd like to know if arcade manager can help me listing all roms reading their filenames like (**kof2002.zip** so it shows - > title: **The King of Fighters 2002** and genre: **Fighting**) so I can sort them and delete all games that I don't want in my collection easily.

Is it possible to do with arcade manager? If not could you please recommend me anything that could do that if you know?

Thank you.

**Comment by cosmo0** [comment]
It can help you clean up your romset but you'll have to use another tool to generate a list.

- Go to http://adb.arcadeitalia.net/lista_mame.php?lang=en
- Click "additional filters"
- In "general" tab click "parent"
- in "driver" tab I advise you to select "emulation: good, imperfect", but it also removes a bunch of playable but buggy games
- In "categories" tab select genre "fighter/versus"
- Run the search
- In "options" (main screen) click "export the result", and choose CSV

You can then use this file in Arcade Manager :)
