### ISSUE TITLE
Overlays game is too large

### ISSUE THREAD

**Issue by halpz** [cosmo0/arcade-manager#4]
when I install overlays, the overlay is fine, but the game underneath is too big, much of it is cut off - 

which settings do I need to change to fix this? should this not be already configured?

i've tried changing the res in the arcade manager 720p, 1080p, 2160p but none of them changed the fact that the game itself is scaled too large

my setup:

retropie 4.4
4k tv
1080p output
Rpi 2 B
mame 0.78 games

**Comment by halpz** [comment]
I've also fiddled in the retroarch menu, but I couldn;'t get it right with integer scaling overlay scaling etc

**Comment by halpz** [comment]
![89bf6e4f-f732-48a5-bf4a-f824c229ca73](https://user-images.githubusercontent.com/3755417/53099152-15f1c280-351d-11e9-8d1b-68761c949719.jpg)

**Comment by mike855** [comment]
Same problem for me

**Comment by mike855** [comment]
Found the solution,

Aspect_ratio_index lust be 23 since retroarch update in common.cfg

**Comment by cosmo0** [comment]
This should have been fixed by that: https://github.com/cosmo0/retropie-overlays-arcade-realistic/issues/4
