### ISSUE TITLE
Feature Request: On-screen ROM list for batch selections and/or delete

### ISSUE THREAD

**Issue by Ltek** [cosmo0/arcade-manager#6]
Being new to ROMs I really like your app - its very helpful. One thing that would make it so much easier for Noobies is to have an on-screen editor allowing us to choose what ROMs to copy over and/or delete.

Especially helps when we have Full ROM sets with clones, etc that we dont yet know much about.

a simple list with check boxes to select, then 'copy' or 'delete' would be great.

thx for considering!

**Comment by cosmo0** [comment]
Sorry for the delay, I hope you have solved your problem by now ^^'

That's what the "manage games list" is for. You can download a pre-built games list, and use it to copy only the good games from your fullset.

Alternatively, you can make a search using http://adb.arcadeitalia.net/lista_mame.php?lang=en, export the results, and use it.
