### ISSUE TITLE
Suggestion: Please add pre-build CSV for MAME 2003-Plus

### ISSUE THREAD

**Issue by nekomania** [cosmo0/arcade-manager#7]
There are many new games being added and non-working games begin fixed in this new core, the old 0.78 set will become obsolete. As suggested I think an updated game list is much needed. Thanks in advance.

**Comment by cosmo0** [comment]
It'll be in the next version.

I don't know why it took me 3 years to think of it (I'm not sure that the feature existed 3 years ago) but: you can take the MAME2003+ DAT file and convert it to CSV using this tool.

DAT file : https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/metadata/mame2003-plus.xml

Then manage games list > convert a DAT file
